chore: update commit-message-check.yml

diff --git a/.github/workflows/commit-message-check.yml b/.github/workflows/commit-message-check.yml
--- a/.github/workflows/commit-message-check.yml
+++ b/.github/workflows/commit-message-check.yml
@@ -9,29 +9,28 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Check Commit Message
-        id: check-commit
+      - name: Check Commit Message Format
         run: |
           commit_message=$(git log -1 --pretty=%B)
-          echo "::set-output name=message::$commit_message"
-
-      - name: Check Commit Message Format
-        if: "!startsWith(steps.check-commit.outputs.message, 'Merge')"
-        uses: gsactions/commit-message-checker@v1
-        with:
-          pattern: '^(feat|chore|test|fix|perf|doc|refactor):'
-          error: 'Commit message does not start with "feat:", "chore:", "test:", "fix:", "perf:", "doc:", or "refactor"'
+          if [[ "$commit_message" != Merge* ]]; then
+            echo "Checking commit message format..."
+            echo "$commit_message" | grep -qE '^(feat|chore|test|fix|perf|doc|refactor):' || {
+              echo "Commit message does not start with 'feat:', 'chore:', 'test:', 'fix:', 'perf:', 'doc:', or 'refactor:'"
+              exit 1
+            }
+          fi
 
       - name: Check Commit Message Length
-        if: "!startsWith(steps.check-commit.outputs.message, 'Merge')"
         run: |
           commit_message=$(git log -1 --pretty=%B)
-          min_length=15
-          actual_length=${#commit_message}
-          if [ $actual_length -lt $min_length ]; then
-            echo "Commit message is too short. It must be at least $min_length characters."
-            echo "Actual message: '$commit_message'"
-            echo "Actual length: $actual_length"
-            echo "Required length: $min_length"
-            exit 1
+          if [[ "$commit_message" != Merge* ]]; then
+            min_length=15
+            actual_length=${#commit_message}
+            if [ $actual_length -lt $min_length ]; then
+              echo "Commit message is too short. It must be at least $min_length characters."
+              echo "Actual message: '$commit_message'"
+              echo "Actual length: $actual_length"
+              echo "Required length: $min_length"
+              exit 1
+            fi
           fi
